export const API_REQUEST = 'API_REQUEST';
export const API_FAILURE = 'API_FAILURE';
export const API_SUCCESS = 'API_SUCCESS';


export const PROFILE_API_REQUEST = 'PROFILE_API_REQUEST';
export const PROFILE_API_FAILURE = 'PROFILE_API_FAILURE';
export const PROFILE_API_SUCCESS = 'PROFILE_API_SUCCESS';